site_name: Apisense Documentation
site_url: https://abelo-smartbee.github.io/apisense-docs/
repo_url: https://github.com/abelo-smartbee/apisense-docs
repo_name: abelo-smartbee/apisense-docs

theme:
  name: material
  language: pl
  logo: assets/logo.svg
  palette:
    - scheme: default
      primary: amber
      accent: orange
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy

plugins:
  - search
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      languages:
        - locale: pl
          name: Polski
          build: true
          default: true
          link: /
          nav:
            - Start: index.md
            - Instrukcja: manual/app-manual.md
            - Opis techniczny: technical/description.md
        - locale: en
          name: English
          build: true
          link: /en/
          nav:
            - Home: index.md
            - User Manual: manual/app-manual.md
            - Technical Description: technical/description.md

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Instrukcja: manual/app-manual.md
  - Opis techniczny: technical/description.md
